name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          node-version: '18.x'
      - uses: hexlet-components/hello-from-hexlet-action
      - run: make say-hello
